/** Generated by `cs2analyzer --generate-ts-fixture`. Do not edit. */

export const grenades = [];
export const shots = [];
export const kills = [];
export const hurts = [];
export const blinds = [];
export const bombEvents = [];
export const buyEvents = [];
export const controllerDump = [];
