/** Generated by `cs2analyzer` tutorial export. Do not edit. */

export const header = {
  "map_name": "de_mirage",
  "tick_rate": 64.0,
  "tick_stride": 6,
  "duration_s": 108.53125,
  "playback_ticks": 6946,
  "team_ct": "Team Spirit",
  "team_t": "Team Vitality",
  "score_ct": 2,
  "score_t": 0
};
