/** Generated by `cs2analyzer` tutorial export. Do not edit. */

export const rounds = [
  {
    "number": 1,
    "start_tick": 0,
    "freeze_end_tick": 0,
    "end_tick": 2277,
    "playback_end_tick": 2577,
    "winner": "CT",
    "win_reason": 8,
    "score_ct": 0,
    "score_t": 0,
    "is_knife": false,
    "team_ct": "Team Spirit",
    "team_t": "Team Vitality"
  },
  {
    "number": 2,
    "start_tick": 3876,
    "freeze_end_tick": 3876,
    "end_tick": 6646,
    "playback_end_tick": 6946,
    "winner": "CT",
    "win_reason": 8,
    "score_ct": 1,
    "score_t": 0,
    "is_knife": false,
    "team_ct": "Team Spirit",
    "team_t": "Team Vitality"
  }
];
