/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_parsedmatch_free: (a: number, b: number) => void;
export const parseDemo: (a: number, b: number, c: number, d: number, e: number) => [number, number, number];
export const parsedmatch_armor: (a: number) => [number, number];
export const parsedmatch_blindsJson: (a: number) => [number, number, number, number];
export const parsedmatch_bombEventsJson: (a: number) => [number, number, number, number];
export const parsedmatch_equip: (a: number) => [number, number];
export const parsedmatch_flags: (a: number) => [number, number];
export const parsedmatch_frameCount: (a: number) => number;
export const parsedmatch_gear: (a: number) => [number, number];
export const parsedmatch_grenadesJson: (a: number) => [number, number, number, number];
export const parsedmatch_headerJson: (a: number) => [number, number, number, number];
export const parsedmatch_health: (a: number) => [number, number];
export const parsedmatch_hurtsJson: (a: number) => [number, number, number, number];
export const parsedmatch_killsJson: (a: number) => [number, number, number, number];
export const parsedmatch_money: (a: number) => [number, number];
export const parsedmatch_playerCount: (a: number) => number;
export const parsedmatch_playersJson: (a: number) => [number, number, number, number];
export const parsedmatch_primary: (a: number) => [number, number];
export const parsedmatch_roundsJson: (a: number) => [number, number, number, number];
export const parsedmatch_secondary: (a: number) => [number, number];
export const parsedmatch_shotsJson: (a: number) => [number, number, number, number];
export const parsedmatch_ticks: (a: number) => [number, number];
export const parsedmatch_x: (a: number) => [number, number];
export const parsedmatch_y: (a: number) => [number, number];
export const parsedmatch_yaw: (a: number) => [number, number];
export const parsedmatch_z: (a: number) => [number, number];
export const start: () => void;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
