/** Generated by `cs2analyzer` tutorial export. Do not edit. */

export const header = {
  "map_name": "de_dust2",
  "tick_rate": 64.0,
  "tick_stride": 6,
  "duration_s": 2776.5938,
  "playback_ticks": 177702,
  "team_ct": "G2",
  "team_t": "Spirit",
  "score_ct": 7,
  "score_t": 12
};
