/** Generated by `cs2analyzer` tutorial export. Do not edit. */

export const players = [
  {
    "index": 0,
    "steam_id": 76561198872013168,
    "name": "tN1R",
    "start_side": "T",
    "is_bot": false
  },
  {
    "index": 1,
    "steam_id": 76561198995880877,
    "name": "zont1x",
    "start_side": "T",
    "is_bot": false
  },
  {
    "index": 2,
    "steam_id": 76561199063238565,
    "name": "magixx",
    "start_side": "T",
    "is_bot": false
  },
  {
    "index": 3,
    "steam_id": 76561198386265483,
    "name": "donk",
    "start_side": "T",
    "is_bot": false
  },
  {
    "index": 4,
    "steam_id": 76561198012872053,
    "name": "huNter",
    "start_side": "CT",
    "is_bot": false
  },
  {
    "index": 5,
    "steam_id": 76561199046478501,
    "name": "MATYS",
    "start_side": "CT",
    "is_bot": false
  },
  {
    "index": 6,
    "steam_id": 76561198081484775,
    "name": "sh1ro",
    "start_side": "T",
    "is_bot": false
  },
  {
    "index": 7,
    "steam_id": 76561198294381090,
    "name": "r1nkle",
    "start_side": "CT",
    "is_bot": false
  },
  {
    "index": 8,
    "steam_id": 76561198068002993,
    "name": "HeavyGod",
    "start_side": "CT",
    "is_bot": false
  },
  {
    "index": 9,
    "steam_id": 76561198053126645,
    "name": "NertZ",
    "start_side": "CT",
    "is_bot": false
  }
];
