/** Generated by `cs2analyzer` tutorial export. Do not edit. */

export const frameCount = 0;
export const playerCount = 0;
export const ticks: number[] = [];
export const x: number[] = [];
export const y: number[] = [];
export const z: number[] = [];
export const yaw: number[] = [];
export const health: number[] = [];
export const armor: number[] = [];
export const flags: number[] = [];
export const money: number[] = [];
export const equip: number[] = [];
export const gear: number[] = [];
export const primary: number[] = [];
export const secondary: number[] = [];
export const active: number[] = [];
export const clip: number[] = [];
export const reserve: number[] = [];
