/** Generated by `cs2analyzer` tutorial export. Do not edit. */

export const header = {
  "map_name": "de_dust2",
  "tick_rate": 64.0,
  "tick_stride": 6,
  "duration_s": 2759.4062,
  "playback_ticks": 176602,
  "team_ct": "Legacy",
  "team_t": "Team Spirit",
  "score_ct": 13,
  "score_t": 7
};
