/** Generated by `cs2analyzer` tutorial export. Do not edit. */

import {
  ticks as ticksA,
  x as xA,
  y as yA,
  z as zA,
  yaw as yawA,
  health as healthA,
  armor as armorA,
  flags as flagsA,
  money as moneyA,
  equip as equipA,
  gear as gearA,
  primary as primaryA,
  secondary as secondaryA,
  active as activeA,
  clip as clipA,
  reserve as reserveA,
} from "./ticks_a";
import {
  ticks as ticksB,
  x as xB,
  y as yB,
  z as zB,
  yaw as yawB,
  health as healthB,
  armor as armorB,
  flags as flagsB,
  money as moneyB,
  equip as equipB,
  gear as gearB,
  primary as primaryB,
  secondary as secondaryB,
  active as activeB,
  clip as clipB,
  reserve as reserveB,
} from "./ticks_b";

export const frameCount = 2159;
export const playerCount = 10;
export const ticks = ticksA.concat(ticksB);
export const x = xA.concat(xB);
export const y = yA.concat(yB);
export const z = zA.concat(zB);
export const yaw = yawA.concat(yawB);
export const health = healthA.concat(healthB);
export const armor = armorA.concat(armorB);
export const flags = flagsA.concat(flagsB);
export const money = moneyA.concat(moneyB);
export const equip = equipA.concat(equipB);
export const gear = gearA.concat(gearB);
export const primary = primaryA.concat(primaryB);
export const secondary = secondaryA.concat(secondaryB);
export const active = activeA.concat(activeB);
export const clip = clipA.concat(clipB);
export const reserve = reserveA.concat(reserveB);
