/** Generated by `cs2analyzer` tutorial export. Do not edit. */

import type { SeriesMatchPayload } from "./types";

export const seriesMatchLoaders: Record<string, () => Promise<SeriesMatchPayload>> = {
  "match-0": () => import("./matches/match-0/payload"),
  "match-1": () => import("./matches/match-1/payload"),
  "match-2": () => import("./matches/match-2/payload"),
  "match-3": () => import("./matches/match-3/payload"),
};
