#!/usr/bin/env bash
# Presence-only parser guards in scripts/run.sh (CI owns byte drift).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
# shellcheck source=scripts/run.sh
. "$ROOT/scripts/run.sh"

fail() {
  echo "fail: $*" >&2
  exit 1
}

parser_artifacts_complete || fail "committed apps/web/src/parser/ should be complete"

scratch="$(mktemp -d)"
trap 'rm -rf "$scratch"' EXIT
PARSER_DIR="$scratch"
parser_artifacts_complete && fail "empty dir should be incomplete"

for name in "${PARSER_ARTIFACTS[@]}"; do
  : >"${scratch}/${name}"
done
parser_artifacts_complete && fail "zero-byte artifacts should be incomplete"

for name in "${PARSER_ARTIFACTS[@]}"; do
  echo ok >"${scratch}/${name}"
done
parser_artifacts_complete || fail "non-empty bindgen outputs should be complete"

missing="${PARSER_ARTIFACTS[0]}"
rm "${scratch}/${missing}"
parser_artifacts_complete && fail "missing ${missing} should be incomplete"

if (have_wasm_toolchain() { return 1; }
  ensure_parser_artifacts) 2>"${scratch}/err"; then
  fail "ensure_parser_artifacts should die without a toolchain"
fi
grep -q 'run scripts/run.sh --build-wasm' "${scratch}/err" || fail "die message should mention --build-wasm"

# --upgrade argument handling. No network: these must fail before cargo/npm.
if "$ROOT/scripts/run.sh" --update --upgrade >"${scratch}/excl.out" 2>"${scratch}/excl.err"; then
  fail "--update and --upgrade together should exit 1"
fi
grep -F -q 'mutually exclusive' "${scratch}/excl.err" || fail "mutual exclusion message"
if "$ROOT/scripts/run.sh" --upgrade --update >"${scratch}/excl.out" 2>"${scratch}/excl.err"; then
  fail "--upgrade and --update together should exit 1"
fi

if "$ROOT/scripts/run.sh" --latest >"${scratch}/latest.out" 2>"${scratch}/latest.err"; then
  fail "--latest alone should exit 1"
fi
grep -F -q -- '--latest requires --upgrade' "${scratch}/latest.err" \
  || fail "--latest alone should say it requires --upgrade"
if "$ROOT/scripts/run.sh" --update --latest >"${scratch}/latest.out" 2>"${scratch}/latest.err"; then
  fail "--latest with --update should exit 1"
fi
grep -F -q -- '--latest requires --upgrade' "${scratch}/latest.err" \
  || fail "--latest with --update should say it requires --upgrade"

"$ROOT/scripts/run.sh" --help >"${scratch}/help.out"
grep -F -q 'warning: --latest drops --peer.' "${scratch}/help.out" \
  || fail "--help should warn that --latest drops --peer"
grep -F -q 'typescript-eslint' "${scratch}/help.out" \
  || fail "--help should warn about typescript-eslint"
grep -F -q 'Vite, Vitest, jsdom, react-router' "${scratch}/help.out" \
  || fail "--help should name major-bump examples"
grep -F -q 'default --upgrade (with --peer) is the safe path' "${scratch}/help.out" \
  || fail "--help should call the default --upgrade the safe path"
help_wide="$(awk 'length > 80 { print length, $0 }' "${scratch}/help.out")"
[[ -z "$help_wide" ]] || fail "--help lines should fit in 80 columns: ${help_wide}"

# Shared skip list for cargo upgrade --exclude and the cargo update filter.
for crate in \
  source2-demo source2-demo-macros source2-demo-protobufs \
  js-sys web-sys \
  wasm-bindgen wasm-bindgen-macro wasm-bindgen-macro-support \
  wasm-bindgen-backend wasm-bindgen-shared wasm-bindgen-futures; do
  upgrade_skips_crate "$crate" || fail "upgrade should skip ${crate}"
done
upgrade_skips_crate serde && fail "upgrade should not skip serde"

skip_lock="${scratch}/skip.lock"
cat >"$skip_lock" <<'EOF'
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "foldhash"
version = "0.1.5"

[[package]]
name = "foldhash"
version = "0.2.0"

[[package]]
name = "serde"
version = "1.0.1"

[[package]]
name = "source2-demo"
version = "0.5.8"

[[package]]
name = "source2-demo-macros"
version = "0.5.8"

[[package]]
name = "source2-demo-protobufs"
version = "0.5.8"

[[package]]
name = "js-sys"
version = "0.3.104"

[[package]]
name = "web-sys"
version = "0.3.77"

[[package]]
name = "wasm-bindgen"
version = "0.2.127"

[[package]]
name = "wasm-bindgen-macro"
version = "0.2.127"

[[package]]
name = "wasm-bindgen-macro-support"
version = "0.2.127"

[[package]]
name = "wasm-bindgen-backend"
version = "0.2.100"

[[package]]
name = "wasm-bindgen-shared"
version = "0.2.127"

[[package]]
name = "wasm-bindgen-futures"
version = "0.4.50"
EOF

all_specs="$(cargo_lock_package_specs "$skip_lock")"
printf '%s\n' "$all_specs" | grep -F -x 'foldhash@0.1.5' >/dev/null \
  || fail "duplicated crates should be emitted as name@version (foldhash@0.1.5)"
printf '%s\n' "$all_specs" | grep -F -x 'foldhash@0.2.0' >/dev/null \
  || fail "duplicated crates should be emitted as name@version (foldhash@0.2.0)"

selected="$(cargo_update_select_specs "$skip_lock")"
printf '%s\n' "$selected" | grep -F -x 'foldhash@0.1.5' >/dev/null \
  || fail "cargo update should pass foldhash@0.1.5"
printf '%s\n' "$selected" | grep -F -x 'foldhash@0.2.0' >/dev/null \
  || fail "cargo update should pass foldhash@0.2.0"
printf '%s\n' "$selected" | grep -F -x 'serde@1.0.1' >/dev/null \
  || fail "cargo update should pass serde@1.0.1"
for skipped in \
  source2-demo@0.5.8 source2-demo-macros@0.5.8 source2-demo-protobufs@0.5.8 \
  js-sys@0.3.104 web-sys@0.3.77 \
  wasm-bindgen@0.2.127 wasm-bindgen-macro@0.2.127 \
  wasm-bindgen-macro-support@0.2.127 wasm-bindgen-backend@0.2.100 \
  wasm-bindgen-shared@0.2.127 wasm-bindgen-futures@0.4.50; do
  if printf '%s\n' "$selected" | grep -F -x "$skipped" >/dev/null; then
    fail "cargo update should skip ${skipped}"
  fi
done

exclude_names="$(upgrade_cargo_exclude_names "$skip_lock")"
for skipped in \
  source2-demo source2-demo-macros source2-demo-protobufs \
  js-sys web-sys \
  wasm-bindgen wasm-bindgen-macro wasm-bindgen-macro-support \
  wasm-bindgen-backend wasm-bindgen-shared wasm-bindgen-futures; do
  printf '%s\n' "$exclude_names" | grep -F -x "$skipped" >/dev/null \
    || fail "cargo upgrade --exclude should name ${skipped}"
done

peer_args="$(LATEST=0 ncu_upgrade_args | paste -sd' ' -)"
[[ "$peer_args" == "-u --peer" ]] || fail "default upgrade should pass --peer (got: ${peer_args})"
latest_args="$(LATEST=1 ncu_upgrade_args | paste -sd' ' -)"
[[ "$latest_args" == "-u" ]] || fail "--latest should drop --peer (got: ${latest_args})"

# Hide cargo-upgrade even when it is installed. run.sh does not put it back on PATH.
if (
  PATH="/usr/bin:/bin"
  hash -r
  require_cargo_edit
) 2>"${scratch}/edit.err"; then
  fail "missing cargo-edit should exit 1"
fi
grep -F -q 'cargo install cargo-edit' "${scratch}/edit.err" \
  || fail "preflight should tell the user to cargo install cargo-edit"

# cmd_upgrade must hit that preflight before any upgrade command.
if (
  require_cargo_edit() {
    die "cargo upgrade (cargo-edit) is missing. Install it with: cargo install cargo-edit"
  }
  cmd_upgrade
) 2>"${scratch}/wire.err"; then
  fail "cmd_upgrade should stop when cargo-edit is missing"
fi
grep -F -q 'cargo install cargo-edit' "${scratch}/wire.err" \
  || fail "cmd_upgrade should run the cargo-edit preflight"
grep -F -q 'failed during: cargo-edit preflight' "${scratch}/wire.err" \
  || fail "preflight failure should name its step"
if grep -F -q 'warning: --latest drops --peer.' "${scratch}/wire.err"; then
  fail "default --upgrade should not print the --latest warning"
fi

if (
  LATEST=1
  require_cargo_edit() {
    die "cargo upgrade (cargo-edit) is missing. Install it with: cargo install cargo-edit"
  }
  cmd_upgrade
) 2>"${scratch}/latest-warn.err"; then
  fail "--upgrade --latest should still stop when cargo-edit is missing"
fi
grep -F -q 'warning: --latest drops --peer.' "${scratch}/latest-warn.err" \
  || fail "--upgrade --latest should warn that it drops --peer"
grep -F -q 'typescript-eslint' "${scratch}/latest-warn.err" \
  || fail "--upgrade --latest should warn about typescript-eslint"
grep -F -q 'Vite, Vitest, jsdom, react-router' "${scratch}/latest-warn.err" \
  || fail "--upgrade --latest should name major-bump examples"
grep -F -q 'default --upgrade (with --peer) is the safe path' "${scratch}/latest-warn.err" \
  || fail "--upgrade --latest should call the default --upgrade the safe path"

guard_repo="${scratch}/guard-repo"
mkdir -p "$guard_repo/apps/web/src/parser" "$guard_repo/crates/demo"
printf '[workspace]\nmembers = ["crates/demo"]\n' >"$guard_repo/Cargo.toml"
printf '[package]\nname = "demo"\nversion = "0.1.0"\n' >"$guard_repo/crates/demo/Cargo.toml"
printf '{}\n' >"$guard_repo/Cargo.lock"
printf '{"name":"web"}\n' >"$guard_repo/apps/web/package.json"
printf '{"lockfileVersion":3,"packages":{}}\n' >"$guard_repo/apps/web/package-lock.json"
printf 'ok\n' >"$guard_repo/apps/web/src/parser/cs2analyzer_wasm.js"
git -C "$guard_repo" init -q
git -C "$guard_repo" add .
git -C "$guard_repo" \
  -c user.email=test@example.com \
  -c user.name=test \
  -c commit.gpgsign=false \
  commit -qm init

(
  ROOT="$guard_repo"
  require_clean_dependency_tree --upgrade
) || fail "clean dependency tree should pass"

echo dirty >>"$guard_repo/README.md"
(
  ROOT="$guard_repo"
  require_clean_dependency_tree --upgrade
) || fail "files outside the dependency tree should be ignored"

printf '\n# dirty\n' >>"$guard_repo/crates/demo/Cargo.toml"
if (ROOT="$guard_repo" require_clean_dependency_tree --upgrade) 2>"${scratch}/dirty.err"; then
  fail "dirty workspace Cargo.toml should be refused"
fi
grep -F -q 'crates/demo/Cargo.toml' "${scratch}/dirty.err" \
  || fail "dirty message should name the Cargo.toml"
grep -F -q 'before running --upgrade' "${scratch}/dirty.err" \
  || fail "dirty message should name --upgrade"
git -C "$guard_repo" checkout -q -- crates/demo/Cargo.toml

printf '\n# dirty\n' >>"$guard_repo/Cargo.lock"
if (ROOT="$guard_repo" require_clean_dependency_tree --update) 2>"${scratch}/dirty.err"; then
  fail "dirty Cargo.lock should be refused"
fi
grep -F -q 'Cargo.lock' "${scratch}/dirty.err" || fail "dirty message should name Cargo.lock"
grep -F -q 'before running --update' "${scratch}/dirty.err" \
  || fail "dirty message should name --update"

# Cargo.lock is still dirty. A failure before any edits must leave it that way.
(
  ROOT="$guard_repo"
  npm_in() { echo "npm_in $*" >>"${scratch}/npm-norestore.log"; }
  UPGRADE_STEP="cargo-edit preflight"
  UPGRADE_MUTATED=0
  UPGRADE_TMP_FILES=()
  false || upgrade_report_failure
) 2>"${scratch}/norestore.err"
grep -F -q 'failed during: cargo-edit preflight' "${scratch}/norestore.err" \
  || fail "preflight failure should name its step"
if grep -F -q 'restored' "${scratch}/norestore.err"; then
  fail "a failure before any edits should not restore the tree"
fi
git -C "$guard_repo" diff --quiet -- Cargo.lock \
  && fail "Cargo.lock should still be dirty before a mutating failure"
test ! -e "${scratch}/npm-norestore.log" \
  || fail "a failure before any edits should not run npm ci"

echo changed >>"$guard_repo/apps/web/src/parser/cs2analyzer_wasm.js"
echo extra >"$guard_repo/apps/web/src/parser/extra.js"
echo 'upgraded' >>"$guard_repo/apps/web/package.json"
(
  ROOT="$guard_repo"
  npm_in() {
    echo "npm_in $*" >>"${scratch}/npm-restore.log"
    return 0
  }
  UPGRADE_STEP="npm install"
  UPGRADE_MUTATED=1
  UPGRADE_TMP_FILES=()
  false || upgrade_report_failure
) 2>"${scratch}/restore.err"
grep -F -q 'failed during: npm install' "${scratch}/restore.err" \
  || fail "restore failure should name the step"
grep -F -q 'restored to its pre-run state' "${scratch}/restore.err" \
  || fail "mutating failure should say the tree was restored"
grep -F -x -q "npm_in ${WEB} ci" "${scratch}/npm-restore.log" \
  || fail "mutating failure should reinstall node_modules with npm ci"
[[ "$(wc -l <"${scratch}/npm-restore.log")" -eq 1 ]] \
  || fail "npm ci should run once when restore succeeds"
git -C "$guard_repo" diff --quiet -- Cargo.lock apps/web/package.json apps/web/src/parser/cs2analyzer_wasm.js \
  || fail "Cargo.lock, package.json, and parser output should be restored"
test ! -e "$guard_repo/apps/web/src/parser/extra.js" \
  || fail "untracked parser file should be removed"
grep -F -q dirty "$guard_repo/README.md" \
  || fail "files outside the dependency tree should stay dirty"

echo 'upgraded again' >>"$guard_repo/apps/web/package-lock.json"
(
  ROOT="$guard_repo"
  npm_in() {
    echo "npm_in $*" >>"${scratch}/npm-ci-fail.log"
    return 1
  }
  UPGRADE_STEP="tests"
  UPGRADE_MUTATED=1
  UPGRADE_TMP_FILES=()
  false || upgrade_report_failure
) 2>"${scratch}/npm-ci-fail.err"
grep -F -q 'failed during: tests' "${scratch}/npm-ci-fail.err" \
  || fail "npm ci failure should still name the upgrade step"
grep -F -q 'Run it manually: (cd apps/web && npm ci)' "${scratch}/npm-ci-fail.err" \
  || fail "a failed npm ci should tell the user to run it manually"
if grep -F -q 'restored to its pre-run state' "${scratch}/npm-ci-fail.err"; then
  fail "a failed npm ci should not claim the install was restored"
fi
[[ "$(wc -l <"${scratch}/npm-ci-fail.log")" -eq 1 ]] \
  || fail "a failed npm ci must not be retried"
git -C "$guard_repo" diff --quiet -- apps/web/package-lock.json \
  || fail "package-lock.json should be restored even when npm ci fails"

echo 'interrupted' >>"$guard_repo/Cargo.lock"
set +e
(
  ROOT="$guard_repo"
  # Called from the interrupt trap; shellcheck does not follow kill into it.
  # shellcheck disable=SC2317
  npm_in() {
    echo "npm_in $*" >>"${scratch}/npm-int.log"
    return 0
  }
  UPGRADE_STEP="tests"
  UPGRADE_MUTATED=1
  UPGRADE_RESTORE_DONE=0
  UPGRADE_TMP_FILES=()
  upgrade_install_traps
  kill -INT "$BASHPID"
  echo 'SIGINT handler did not exit' >&2
  exit 1
) 2>"${scratch}/int.err"
int_status=$?
set -e
[[ "$int_status" -eq 130 ]] || fail "SIGINT should exit 130 (got ${int_status})"
grep -F -q 'interrupted during: tests' "${scratch}/int.err" \
  || fail "SIGINT should name the step"
grep -F -q 'restored to its pre-run state' "${scratch}/int.err" \
  || fail "SIGINT should restore the dependency tree"
grep -F -x -q "npm_in ${WEB} ci" "${scratch}/npm-int.log" \
  || fail "SIGINT should reinstall node_modules with npm ci"
[[ "$(wc -l <"${scratch}/npm-int.log")" -eq 1 ]] \
  || fail "SIGINT and the EXIT trap should npm ci only once"
git -C "$guard_repo" diff --quiet -- Cargo.lock \
  || fail "Cargo.lock should be restored after SIGINT"

echo 'terminated' >>"$guard_repo/apps/web/package.json"
set +e
(
  ROOT="$guard_repo"
  # Called from the interrupt trap; shellcheck does not follow kill into it.
  # shellcheck disable=SC2317
  npm_in() {
    echo "npm_in $*" >>"${scratch}/npm-term.log"
    return 0
  }
  UPGRADE_STEP="cargo test"
  UPGRADE_MUTATED=1
  UPGRADE_RESTORE_DONE=0
  UPGRADE_TMP_FILES=()
  upgrade_install_traps
  kill -TERM "$BASHPID"
  echo 'SIGTERM handler did not exit' >&2
  exit 1
) 2>"${scratch}/term.err"
term_status=$?
set -e
[[ "$term_status" -eq 143 ]] || fail "SIGTERM should exit 143 (got ${term_status})"
grep -F -q 'interrupted during: cargo test' "${scratch}/term.err" \
  || fail "SIGTERM should name the step"
grep -F -x -q "npm_in ${WEB} ci" "${scratch}/npm-term.log" \
  || fail "SIGTERM should reinstall node_modules with npm ci"
[[ "$(wc -l <"${scratch}/npm-term.log")" -eq 1 ]] \
  || fail "SIGTERM and the EXIT trap should npm ci only once"
git -C "$guard_repo" diff --quiet -- apps/web/package.json \
  || fail "package.json should be restored after SIGTERM"

echo 'during restore' >>"$guard_repo/Cargo.lock"
set +e
(
  ROOT="$guard_repo"
  # Second SIGINT is raised from inside the restore's npm ci.
  # shellcheck disable=SC2317
  npm_in() {
    echo "npm_in $*" >>"${scratch}/npm-int-during.log"
    kill -INT "$BASHPID"
    return 1
  }
  UPGRADE_STEP="npm install"
  UPGRADE_MUTATED=1
  UPGRADE_RESTORE_DONE=0
  UPGRADE_TMP_FILES=()
  upgrade_install_traps
  kill -INT "$BASHPID"
  echo 'handler did not exit' >&2
  exit 1
) 2>"${scratch}/int-during.err"
during_status=$?
set -e
[[ "$during_status" -eq 130 ]] \
  || fail "SIGINT during restore should exit 130 (got ${during_status})"
[[ "$(grep -F -c 'interrupted during:' "${scratch}/int-during.err")" -eq 1 ]] \
  || fail "interrupted-during should print once when restore is interrupted"
grep -F -q 'interrupted during: npm install' "${scratch}/int-during.err" \
  || fail "the first SIGINT should name the original step"
[[ "$(grep -F -c 'interrupted while restoring; check git status, then run (cd apps/web && npm ci)' "${scratch}/int-during.err")" -eq 1 ]] \
  || fail "SIGINT during restore should print the git status and npm ci hint once"
[[ "$(wc -l <"${scratch}/npm-int-during.log")" -eq 1 ]] \
  || fail "SIGINT during restore must not start npm ci again"
git -C "$guard_repo" diff --quiet -- Cargo.lock \
  || fail "lockfiles restored before npm ci should stay restored"

# 0.x minor bumps count as major; 1.x minor bumps do not.
is_major_bump 1.2.3 2.0.0 || fail "1.x to 2.x is a major bump"
is_major_bump 1.2.3 1.9.0 && fail "1.x minor is not a major bump"
is_major_bump 0.2.1 0.3.0 || fail "0.x minor is a major bump"
is_major_bump 0.2.1 0.2.9 && fail "0.x patch is not a major bump"
is_major_bump 0.9.0 1.0.0 || fail "0.x to 1.x is a major bump"
is_major_bump 2.0.0 1.5.0 && fail "a downgrade is not a major bump"
version_list_is_major_bump "1.0.0,2.0.0" "2.0.1" && fail "highest version staying on 2.0 is not major"
version_list_is_major_bump "0.2.4" "0.4.0,0.2.5" || fail "0.x minor among versions is major"

echo "scripts/run.test.sh: ok"
