/** Generated by `cs2analyzer` tutorial export. Do not edit. */

export const header = {
  "map_name": "de_dust2",
  "tick_rate": 64.0,
  "tick_stride": 6,
  "duration_s": 3244.1406,
  "playback_ticks": 207625,
  "team_ct": "B8 Esports",
  "team_t": "Team Spirit",
  "score_ct": 11,
  "score_t": 11
};
