/** Generated by `cs2analyzer` tutorial export. Do not edit. */

export const players = [
  {
    "index": 0,
    "steam_id": 76561198305036904,
    "name": "npl",
    "start_side": "CT",
    "is_bot": false
  },
  {
    "index": 1,
    "steam_id": 76561199149812353,
    "name": "esenthial",
    "start_side": "CT",
    "is_bot": false
  },
  {
    "index": 2,
    "steam_id": 76561198081484775,
    "name": "sh1ro",
    "start_side": "T",
    "is_bot": false
  },
  {
    "index": 3,
    "steam_id": 76561199063238565,
    "name": "magixx",
    "start_side": "T",
    "is_bot": false
  },
  {
    "index": 4,
    "steam_id": 76561198872013168,
    "name": "tN1R",
    "start_side": "T",
    "is_bot": false
  },
  {
    "index": 5,
    "steam_id": 76561198995880877,
    "name": "zont1x",
    "start_side": "T",
    "is_bot": false
  },
  {
    "index": 6,
    "steam_id": 76561198304115519,
    "name": "alex666",
    "start_side": "CT",
    "is_bot": false
  },
  {
    "index": 7,
    "steam_id": 76561198386265483,
    "name": "donk",
    "start_side": "T",
    "is_bot": false
  },
  {
    "index": 8,
    "steam_id": 76561198382173659,
    "name": "kensizor",
    "start_side": "CT",
    "is_bot": false
  },
  {
    "index": 9,
    "steam_id": 76561199001538362,
    "name": "s1zzi",
    "start_side": "CT",
    "is_bot": false
  }
];
