//! Compact two-round tutorial Replay → TypeScript under `apps/web/src/lib/tutorial/`.
//!
//! Post-process of the same [`Match`] the JSON dump uses: pick the first live
//! regulation rounds, remap ticks so the slice starts near 0, and emit modules
//! the web hydrate helper can turn into a `Replay`.

use std::path::{Path, PathBuf};

use cs2analyzer::{
    Blind, BombEvent, BuyEvent, ControllerDump, GrenadeThrow, Hurt, Kill, Match, MatchHeader,
    Round, Shot, Side, TickBuffer, DEFAULT_TICK_RATE, FIRST_OVERTIME_ROUND,
};
use serde::Serialize;

/// Live non-knife regulation rounds in the checked-in tutorial fixture.
pub const TUTORIAL_LIVE_ROUNDS: u32 = 2;

/// Snapshot stride when `--stride` is omitted: ~10 Hz on 64-tick GOTV.
const TUTORIAL_SNAPSHOT_HZ: u32 = 10;

/// Keep one tick snapshot every N demo ticks for a compact tutorial parse.
pub const TUTORIAL_TICK_STRIDE: u32 = DEFAULT_TICK_RATE as u32 / TUTORIAL_SNAPSHOT_HZ;

/// Split SoA arrays across `ticks_a.ts` / `ticks_b.ts` above this many values.
pub const TS_SHARD_VALUE_THRESHOLD: usize = 12_000;

pub(crate) const GENERATED_BANNER: &str =
    "/** Generated by `cs2analyzer` tutorial export. Do not edit. */\n";

const STALE_SHARDS: [&str; 2] = ["ticks_a.ts", "ticks_b.ts"];

/// Two-round window after tick remapping.
#[derive(Debug)]
pub struct TutorialSlice {
    pub sliced: Match,
    pub origin_tick: u32,
}

/// One TypeScript module to write (file name relative to the tutorial dir).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedFile {
    pub name: String,
    pub contents: String,
}

/// Sizes after a successful write.
pub struct WriteSummary {
    pub files: Vec<(String, usize)>,
    pub frame_count: u32,
    pub player_count: u32,
    pub round_count: usize,
    pub map_name: String,
    pub origin_tick: u32,
}

/// First `live_rounds` non-knife regulation rounds, ticks shifted to start near 0.
pub fn slice_tutorial_match(m: &Match, live_rounds: u32) -> Result<TutorialSlice, String> {
    let count = live_rounds.max(1) as usize;
    let selected = select_regulation_rounds(&m.rounds, count)?;
    let start_tick = selected
        .first()
        .map(|r| r.start_tick)
        .ok_or_else(|| "no rounds selected".to_string())?;
    let end_tick = selected
        .last()
        .map(round_window_end)
        .ok_or_else(|| "no rounds selected".to_string())?;
    if end_tick < start_tick {
        return Err("selected rounds have an empty tick window".to_string());
    }
    let origin = start_tick;
    let mut rounds = selected;
    for round in &mut rounds {
        remap_round(round, origin);
    }
    let (score_ct, score_t) = header_scores(&rounds);
    let playback_ticks = end_tick.saturating_sub(origin);
    let tick_rate = m.header.tick_rate.max(1.0);
    let header = MatchHeader {
        map_name: m.header.map_name.clone(),
        tick_rate: m.header.tick_rate,
        tick_stride: m.header.tick_stride,
        duration_s: playback_ticks as f32 / tick_rate,
        playback_ticks,
        team_ct: m.header.team_ct.clone(),
        team_t: m.header.team_t.clone(),
        score_ct,
        score_t,
    };
    Ok(TutorialSlice {
        sliced: Match {
            header,
            players: m.players.clone(),
            rounds,
            ticks: slice_ticks_windows(&m.ticks, &[(start_tick, end_tick)], origin),
            grenades: slice_grenades(&m.grenades, &[(start_tick, end_tick)], origin),
            shots: slice_shots(&m.shots, &[(start_tick, end_tick)], origin),
            kills: slice_kills(&m.kills, &[(start_tick, end_tick)], origin),
            hurts: slice_hurts(&m.hurts, &[(start_tick, end_tick)], origin),
            blinds: slice_blinds(&m.blinds, &[(start_tick, end_tick)], origin),
            bomb_events: slice_bomb_events(&m.bomb_events, &[(start_tick, end_tick)], origin),
            buy_events: slice_buy_events(&m.buy_events, &[(start_tick, end_tick)], origin),
            stats: Vec::new(),
            controller_dump: slice_controller_dump(
                &m.controller_dump,
                &[(start_tick, end_tick)],
                origin,
            ),
        },
        origin_tick: origin,
    })
}

pub(crate) fn select_regulation_rounds(
    rounds: &[Round],
    count: usize,
) -> Result<Vec<Round>, String> {
    let live: Vec<Round> = rounds
        .iter()
        .filter(|round| !round.is_knife && round.number > 0 && round.number < FIRST_OVERTIME_ROUND)
        .cloned()
        .collect();
    if live.len() < count {
        return Err(format!(
            "demo has {} non-knife regulation round{}, need {count} for the tutorial fixture",
            live.len(),
            if live.len() == 1 { "" } else { "s" }
        ));
    }
    Ok(live.into_iter().take(count).collect())
}

pub(crate) fn round_window_end(round: &Round) -> u32 {
    round.end_tick.max(round.playback_end_tick)
}

pub(crate) fn remap_tick(tick: u32, origin: u32) -> u32 {
    tick.saturating_sub(origin)
}

pub(crate) fn remap_round(round: &mut Round, origin: u32) {
    round.start_tick = remap_tick(round.start_tick, origin);
    round.freeze_end_tick = remap_tick(round.freeze_end_tick, origin);
    round.end_tick = remap_tick(round.end_tick, origin);
    if round.playback_end_tick > 0 {
        round.playback_end_tick = remap_tick(round.playback_end_tick, origin);
    }
}

pub(crate) fn header_scores(rounds: &[Round]) -> (i32, i32) {
    let mut score_ct = 0;
    let mut score_t = 0;
    for round in rounds {
        match round.winner {
            Some(Side::Ct) => score_ct += 1,
            Some(Side::T) => score_t += 1,
            None => {}
        }
    }
    (score_ct, score_t)
}

pub(crate) fn slice_ticks_windows(
    buf: &TickBuffer,
    windows: &[(u32, u32)],
    origin: u32,
) -> TickBuffer {
    let player_count = buf.player_count as usize;
    let frames: Vec<usize> = buf
        .ticks
        .iter()
        .enumerate()
        .filter(|(_, tick)| in_any_window(**tick, windows))
        .map(|(index, _)| index)
        .collect();
    TickBuffer {
        frame_count: frames.len() as u32,
        player_count: buf.player_count,
        ticks: frames
            .iter()
            .filter_map(|&frame| buf.ticks.get(frame).copied())
            .map(|tick| remap_tick(tick, origin))
            .collect(),
        x: copy_player_field(&buf.x, &frames, player_count),
        y: copy_player_field(&buf.y, &frames, player_count),
        z: copy_player_field(&buf.z, &frames, player_count),
        yaw: copy_player_field(&buf.yaw, &frames, player_count),
        health: copy_player_field(&buf.health, &frames, player_count),
        armor: copy_player_field(&buf.armor, &frames, player_count),
        flags: copy_player_field(&buf.flags, &frames, player_count),
        money: copy_player_field(&buf.money, &frames, player_count),
        equip: copy_player_field(&buf.equip, &frames, player_count),
        gear: copy_player_field(&buf.gear, &frames, player_count),
        primary: copy_player_field(&buf.primary, &frames, player_count),
        secondary: copy_player_field(&buf.secondary, &frames, player_count),
        active: copy_player_field(&buf.active, &frames, player_count),
        clip: copy_player_field(&buf.clip, &frames, player_count),
        reserve: copy_player_field(&buf.reserve, &frames, player_count),
    }
}

fn copy_player_field<T: Copy + Default>(
    src: &[T],
    frames: &[usize],
    player_count: usize,
) -> Vec<T> {
    let mut out = Vec::with_capacity(frames.len().saturating_mul(player_count));
    for &frame in frames {
        let base = frame.saturating_mul(player_count);
        for offset in 0..player_count {
            out.push(src.get(base + offset).copied().unwrap_or_default());
        }
    }
    out
}

fn in_window(tick: u32, start_tick: u32, end_tick: u32) -> bool {
    tick >= start_tick && tick <= end_tick
}

pub(crate) fn in_any_window(tick: u32, windows: &[(u32, u32)]) -> bool {
    windows
        .iter()
        .any(|&(start_tick, end_tick)| in_window(tick, start_tick, end_tick))
}

/// Seconds after freeze end, clamped to the same prefs range as the viewer.
pub fn clamp_habits_window_sec(value: u32) -> u32 {
    value.clamp(
        cs2analyzer::SERIES_HABITS_WINDOW_MIN_SECONDS,
        cs2analyzer::SERIES_HABITS_WINDOW_MAX_SECONDS,
    )
}

/// Inclusive `[freeze_end, freeze_end + window]` clipped to the round end.
pub fn habits_window_for_round(round: &Round, tick_rate: f32, window_sec: u32) -> (u32, u32) {
    let start = if round.freeze_end_tick > 0 {
        round.freeze_end_tick
    } else {
        round.start_tick
    };
    let span = (clamp_habits_window_sec(window_sec) as f32 * tick_rate.max(1.0)).round() as u32;
    let end = start.saturating_add(span).min(round_window_end(round));
    (start, end)
}

pub(crate) fn slice_grenades(
    grenades: &[GrenadeThrow],
    windows: &[(u32, u32)],
    origin: u32,
) -> Vec<GrenadeThrow> {
    grenades
        .iter()
        .filter(|throw| in_any_window(throw.start_tick, windows))
        .cloned()
        .map(|mut throw| {
            throw.start_tick = remap_tick(throw.start_tick, origin);
            throw.detonate_tick = remap_tick(throw.detonate_tick, origin);
            throw.end_tick = remap_tick(throw.end_tick, origin);
            for point in &mut throw.points {
                point.tick = remap_tick(point.tick, origin);
            }
            for fire in &mut throw.fires {
                fire.start_tick = remap_tick(fire.start_tick, origin);
                fire.end_tick = remap_tick(fire.end_tick, origin);
            }
            throw
        })
        .collect()
}

pub(crate) fn slice_shots(shots: &[Shot], windows: &[(u32, u32)], origin: u32) -> Vec<Shot> {
    shots
        .iter()
        .filter(|shot| in_any_window(shot.tick, windows))
        .copied()
        .map(|mut shot| {
            shot.tick = remap_tick(shot.tick, origin);
            shot
        })
        .collect()
}

pub(crate) fn slice_kills(kills: &[Kill], windows: &[(u32, u32)], origin: u32) -> Vec<Kill> {
    kills
        .iter()
        .filter(|kill| in_any_window(kill.tick, windows))
        .cloned()
        .map(|mut kill| {
            kill.tick = remap_tick(kill.tick, origin);
            kill
        })
        .collect()
}

pub(crate) fn slice_hurts(hurts: &[Hurt], windows: &[(u32, u32)], origin: u32) -> Vec<Hurt> {
    hurts
        .iter()
        .filter(|hurt| in_any_window(hurt.tick, windows))
        .cloned()
        .map(|mut hurt| {
            hurt.tick = remap_tick(hurt.tick, origin);
            hurt
        })
        .collect()
}

pub(crate) fn slice_blinds(blinds: &[Blind], windows: &[(u32, u32)], origin: u32) -> Vec<Blind> {
    blinds
        .iter()
        .filter(|blind| in_any_window(blind.tick, windows))
        .copied()
        .map(|mut blind| {
            blind.tick = remap_tick(blind.tick, origin);
            blind
        })
        .collect()
}

pub(crate) fn slice_bomb_events(
    events: &[BombEvent],
    windows: &[(u32, u32)],
    origin: u32,
) -> Vec<BombEvent> {
    events
        .iter()
        .filter(|event| in_any_window(event.tick, windows))
        .cloned()
        .map(|mut event| {
            event.tick = remap_tick(event.tick, origin);
            event
        })
        .collect()
}

pub(crate) fn slice_buy_events(
    events: &[BuyEvent],
    windows: &[(u32, u32)],
    origin: u32,
) -> Vec<BuyEvent> {
    events
        .iter()
        .filter(|event| in_any_window(event.tick, windows))
        .cloned()
        .map(|mut event| {
            event.tick = remap_tick(event.tick, origin);
            event
        })
        .collect()
}

pub(crate) fn slice_controller_dump(
    dump: &[ControllerDump],
    windows: &[(u32, u32)],
    origin: u32,
) -> Vec<ControllerDump> {
    dump.iter()
        .filter(|row| in_any_window(row.tick, windows))
        .cloned()
        .map(|mut row| {
            row.tick = remap_tick(row.tick, origin);
            row
        })
        .collect()
}

/// TypeScript modules for a sliced match (header, players, rounds, events, ticks).
pub fn emit_match_modules(
    sliced: &Match,
    shard_after: usize,
) -> Result<Vec<GeneratedFile>, String> {
    let mut files = vec![
        module_file("header.ts", &export_json("header", &sliced.header, true)?)?,
        module_file(
            "players.ts",
            &export_json("players", &sliced.players, true)?,
        )?,
        module_file("rounds.ts", &export_json("rounds", &sliced.rounds, true)?)?,
        module_file("events.ts", &emit_events(sliced)?)?,
    ];
    files.extend(emit_ticks(&sliced.ticks, shard_after)?);
    Ok(files)
}

/// Single-tutorial modules, including `constants.ts`.
pub fn emit_tutorial_files(
    sliced: &Match,
    shard_after: usize,
) -> Result<Vec<GeneratedFile>, String> {
    let mut files = vec![GeneratedFile {
        name: "constants.ts".to_string(),
        contents: emit_constants(&sliced.header.map_name)?,
    }];
    files.extend(emit_match_modules(sliced, shard_after)?);
    Ok(files)
}

fn emit_constants(map_name: &str) -> Result<String, String> {
    let map = serde_json::to_string(map_name).map_err(|e| e.to_string())?;
    Ok(format!(
        "/** Tutorial demo identity. There is no real `.dem` in git; the File is a name stub. */\n\
         export const TUTORIAL_FILENAME = \"tutorial.dem\";\n\
         \n\
         export const TUTORIAL_MAP = {map};\n\
         \n\
         export const TUTORIAL_ID = `tutorial|${{TUTORIAL_MAP}}`;\n"
    ))
}

fn emit_events(sliced: &Match) -> Result<String, String> {
    let mut body = String::new();
    body.push_str(&export_json("grenades", &sliced.grenades, true)?);
    body.push_str(&export_json("shots", &sliced.shots, false)?);
    body.push_str(&export_json("kills", &sliced.kills, true)?);
    body.push_str(&export_json("hurts", &sliced.hurts, false)?);
    body.push_str(&export_json("blinds", &sliced.blinds, false)?);
    body.push_str(&export_json("bombEvents", &sliced.bomb_events, true)?);
    body.push_str(&export_json("buyEvents", &sliced.buy_events, false)?);
    body.push_str(&export_json(
        "controllerDump",
        &sliced.controller_dump,
        true,
    )?);
    Ok(body)
}

fn emit_ticks(buf: &TickBuffer, shard_after: usize) -> Result<Vec<GeneratedFile>, String> {
    let values = (buf.frame_count as usize).saturating_mul(buf.player_count as usize);
    if values > shard_after && buf.frame_count > 1 {
        emit_sharded_ticks(buf)
    } else {
        let mut body = export_u32("frameCount", buf.frame_count);
        body.push_str(&export_u32("playerCount", buf.player_count));
        body.push_str(&emit_tick_arrays(buf)?);
        Ok(vec![module_file("ticks.ts", &body)?])
    }
}

fn emit_sharded_ticks(buf: &TickBuffer) -> Result<Vec<GeneratedFile>, String> {
    let mid = (buf.frame_count as usize) / 2;
    let left = tick_frame_range(buf, 0, mid);
    let right = tick_frame_range(buf, mid, buf.frame_count as usize);
    let a = emit_tick_arrays(&left)?;
    let b = emit_tick_arrays(&right)?;
    let mut ticks = String::from("import {\n");
    ticks.push_str(&shard_import_list("A"));
    ticks.push_str("} from \"./ticks_a\";\nimport {\n");
    ticks.push_str(&shard_import_list("B"));
    ticks.push_str("} from \"./ticks_b\";\n\n");
    ticks.push_str(&export_u32("frameCount", buf.frame_count));
    ticks.push_str(&export_u32("playerCount", buf.player_count));
    for name in TICK_ARRAY_NAMES {
        ticks.push_str(&format!("export const {name} = {name}A.concat({name}B);\n"));
    }
    Ok(vec![
        module_file("ticks_a.ts", &a)?,
        module_file("ticks_b.ts", &b)?,
        module_file("ticks.ts", &ticks)?,
    ])
}

const TICK_ARRAY_NAMES: [&str; 16] = [
    "ticks",
    "x",
    "y",
    "z",
    "yaw",
    "health",
    "armor",
    "flags",
    "money",
    "equip",
    "gear",
    "primary",
    "secondary",
    "active",
    "clip",
    "reserve",
];

fn shard_import_list(suffix: &str) -> String {
    let mut out = String::new();
    for name in TICK_ARRAY_NAMES {
        out.push_str(&format!("  {name} as {name}{suffix},\n"));
    }
    out
}

fn tick_frame_range(buf: &TickBuffer, start_frame: usize, end_frame: usize) -> TickBuffer {
    let player_count = buf.player_count as usize;
    let frames: Vec<usize> = (start_frame..end_frame).collect();
    TickBuffer {
        frame_count: frames.len() as u32,
        player_count: buf.player_count,
        ticks: frames
            .iter()
            .filter_map(|&frame| buf.ticks.get(frame).copied())
            .collect(),
        x: copy_player_field(&buf.x, &frames, player_count),
        y: copy_player_field(&buf.y, &frames, player_count),
        z: copy_player_field(&buf.z, &frames, player_count),
        yaw: copy_player_field(&buf.yaw, &frames, player_count),
        health: copy_player_field(&buf.health, &frames, player_count),
        armor: copy_player_field(&buf.armor, &frames, player_count),
        flags: copy_player_field(&buf.flags, &frames, player_count),
        money: copy_player_field(&buf.money, &frames, player_count),
        equip: copy_player_field(&buf.equip, &frames, player_count),
        gear: copy_player_field(&buf.gear, &frames, player_count),
        primary: copy_player_field(&buf.primary, &frames, player_count),
        secondary: copy_player_field(&buf.secondary, &frames, player_count),
        active: copy_player_field(&buf.active, &frames, player_count),
        clip: copy_player_field(&buf.clip, &frames, player_count),
        reserve: copy_player_field(&buf.reserve, &frames, player_count),
    }
}

fn emit_tick_arrays(buf: &TickBuffer) -> Result<String, String> {
    let mut body = String::new();
    body.push_str(&export_json("ticks", &buf.ticks, false)?);
    body.push_str(&export_json("x", &buf.x, false)?);
    body.push_str(&export_json("y", &buf.y, false)?);
    body.push_str(&export_json("z", &buf.z, false)?);
    body.push_str(&export_json("yaw", &buf.yaw, false)?);
    body.push_str(&export_json("health", &buf.health, false)?);
    body.push_str(&export_json("armor", &buf.armor, false)?);
    body.push_str(&export_json("flags", &buf.flags, false)?);
    body.push_str(&export_json("money", &buf.money, false)?);
    body.push_str(&export_json("equip", &buf.equip, false)?);
    body.push_str(&export_json("gear", &buf.gear, false)?);
    body.push_str(&export_json("primary", &buf.primary, false)?);
    body.push_str(&export_json("secondary", &buf.secondary, false)?);
    body.push_str(&export_json("active", &buf.active, false)?);
    body.push_str(&export_json("clip", &buf.clip, false)?);
    body.push_str(&export_json("reserve", &buf.reserve, false)?);
    Ok(body)
}

fn export_u32(name: &str, value: u32) -> String {
    format!("export const {name} = {value};\n")
}

fn export_json(name: &str, value: &impl Serialize, pretty: bool) -> Result<String, String> {
    let json = if pretty {
        serde_json::to_string_pretty(value).map_err(|e| e.to_string())?
    } else {
        serde_json::to_string(value).map_err(|e| e.to_string())?
    };
    Ok(format!("export const {name} = {json};\n"))
}

pub(crate) fn module_file(name: &str, body: &str) -> Result<GeneratedFile, String> {
    let mut contents = String::from(GENERATED_BANNER);
    contents.push('\n');
    contents.push_str(body);
    if !body.ends_with('\n') {
        contents.push('\n');
    }
    Ok(GeneratedFile {
        name: name.to_string(),
        contents,
    })
}

/// Write generated modules into `dir`, creating it when needed.
///
/// `hydrate_source` is the hand-written `hydrate.ts` (written only when missing
/// so later tour-loader edits are not clobbered).
pub fn write_tutorial_files(
    dir: &Path,
    files: &[GeneratedFile],
    hydrate_source: Option<&str>,
) -> Result<Vec<(String, usize)>, String> {
    std::fs::create_dir_all(dir).map_err(|e| format!("cannot create {}: {e}", dir.display()))?;
    remove_stale_shards(dir, files)?;
    let mut written = Vec::new();
    for file in files {
        let path = dir.join(&file.name);
        std::fs::write(&path, file.contents.as_bytes())
            .map_err(|e| format!("cannot write {}: {e}", path.display()))?;
        written.push((file.name.clone(), file.contents.len()));
    }
    if let Some(source) = hydrate_source {
        let path = dir.join("hydrate.ts");
        if !path.exists() {
            std::fs::write(&path, source.as_bytes())
                .map_err(|e| format!("cannot write {}: {e}", path.display()))?;
            written.push(("hydrate.ts".to_string(), source.len()));
        }
    }
    Ok(written)
}

fn remove_stale_shards(dir: &Path, files: &[GeneratedFile]) -> Result<(), String> {
    for name in STALE_SHARDS {
        if files.iter().any(|file| file.name == name) {
            continue;
        }
        let path = dir.join(name);
        if path.exists() {
            std::fs::remove_file(&path)
                .map_err(|e| format!("cannot remove stale {}: {e}", path.display()))?;
        }
    }
    Ok(())
}

/// Slice, emit, and write. `start` is the cwd (or any path inside the repo).
pub fn write_tutorial_fixture(
    dir: &Path,
    slice: &TutorialSlice,
    shard_after: usize,
    hydrate_source: Option<&str>,
) -> Result<WriteSummary, String> {
    let files = emit_tutorial_files(&slice.sliced, shard_after)?;
    let written = write_tutorial_files(dir, &files, hydrate_source)?;
    Ok(WriteSummary {
        files: written,
        frame_count: slice.sliced.ticks.frame_count,
        player_count: slice.sliced.ticks.player_count,
        round_count: slice.sliced.rounds.len(),
        map_name: slice.sliced.header.map_name.clone(),
        origin_tick: slice.origin_tick,
    })
}

/// `apps/web/src/lib/tutorial` by walking up from `start`, then the cargo workspace.
pub fn discover_tutorial_dir(start: &Path) -> Result<PathBuf, String> {
    let mut cursor = if start.is_absolute() {
        start.to_path_buf()
    } else {
        std::env::current_dir()
            .map_err(|e| format!("cannot read cwd: {e}"))?
            .join(start)
    };
    if cursor.is_file() {
        cursor.pop();
    }
    let mut walk = cursor;
    loop {
        if let Some(found) = tutorial_dir_under(&walk) {
            return Ok(found);
        }
        if !walk.pop() {
            break;
        }
    }
    let crate_root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..");
    if let Some(found) = tutorial_dir_under(&crate_root) {
        return Ok(found);
    }
    Err(
        "cannot find apps/web/src/lib — run from the cs2analyzer repo \
         (walks up from cwd, or uses the cargo workspace root)"
            .into(),
    )
}

fn tutorial_dir_under(root: &Path) -> Option<PathBuf> {
    let lib = root.join("apps/web/src/lib");
    lib.is_dir().then(|| lib.join("tutorial"))
}

#[cfg(test)]
/// Competitive freeze + live play used only when no `.dem` is available.
pub const ESTIMATE_FULL_ROUND_SECONDS: u32 = 115;

#[cfg(test)]
/// Typical GOTV pawn count for size estimates.
pub const ESTIMATE_PLAYER_COUNT: u32 = 10;

/// Frames kept for `seconds` of play at `tick_rate` / `stride`.
#[cfg(test)]
pub fn estimated_frame_count(seconds: u32, tick_rate: f32, stride: u32) -> u32 {
    let hz = tick_rate.max(1.0) / stride.max(1) as f32;
    (seconds as f32 * hz).round() as u32
}

/// Representative SoA buffer (world-ish floats, 64-tick stride labels).
#[cfg(test)]
pub fn synthetic_tick_buffer(frame_count: u32, player_count: u32, stride: u32) -> TickBuffer {
    let n = (frame_count as usize).saturating_mul(player_count as usize);
    let ticks = (0..frame_count).map(|i| i.saturating_mul(stride)).collect();
    TickBuffer {
        frame_count,
        player_count,
        ticks,
        x: vec![1234.5; n],
        y: vec![-890.25; n],
        z: vec![64.0; n],
        yaw: vec![180.0; n],
        health: vec![100; n],
        armor: vec![100; n],
        flags: vec![3; n],
        money: vec![8000; n],
        equip: vec![4700; n],
        gear: vec![72; n],
        primary: vec![7; n],
        secondary: vec![1; n],
        active: vec![7; n],
        clip: vec![30; n],
        reserve: vec![90; n],
    }
}

/// Uncompressed TypeScript bytes for a synthetic tick module (and optional extras).
#[cfg(test)]
pub fn measure_emitted_bytes(files: &[GeneratedFile]) -> usize {
    files.iter().map(|file| file.contents.len()).sum()
}

#[cfg(test)]
mod tests {
    use super::*;
    use cs2analyzer::{FireCell, GrenadeKind, GrenadePoint, Player};

    fn empty_header() -> MatchHeader {
        MatchHeader {
            map_name: "de_mirage".into(),
            tick_rate: 64.0,
            tick_stride: 6,
            duration_s: 80.0,
            playback_ticks: 5000,
            team_ct: "CT".into(),
            team_t: "T".into(),
            score_ct: 13,
            score_t: 11,
        }
    }

    fn player(index: u8, name: &str, side: Side) -> Player {
        Player {
            index,
            steam_id: u64::from(index) + 1,
            name: name.into(),
            start_side: side,
            is_bot: false,
        }
    }

    fn live_round(number: u32, start: u32, freeze: u32, end: u32) -> Round {
        Round {
            number,
            start_tick: start,
            freeze_end_tick: freeze,
            end_tick: end,
            playback_end_tick: end + 16,
            winner: Some(if number % 2 == 1 { Side::Ct } else { Side::T }),
            win_reason: 8,
            score_ct: 0,
            score_t: 0,
            is_knife: false,
            team_ct: "CT".into(),
            team_t: "T".into(),
        }
    }

    fn knife_round(start: u32, end: u32) -> Round {
        Round {
            number: 0,
            start_tick: start,
            freeze_end_tick: start + 10,
            end_tick: end,
            playback_end_tick: 0,
            winner: Some(Side::T),
            win_reason: 1,
            score_ct: 0,
            score_t: 0,
            is_knife: true,
            team_ct: "CT".into(),
            team_t: "T".into(),
        }
    }

    fn kill(tick: u32) -> Kill {
        Kill {
            tick,
            attacker: 0,
            victim: 1,
            assister: -1,
            weapon: "ak47".into(),
            headshot: false,
            assisted_flash: false,
            wallbang: false,
            noscope: false,
            through_smoke: false,
            attacker_blind: false,
            attacker_airborne: false,
            x: 1.0,
            y: 2.0,
            z: 3.0,
            attacker_x: 4.0,
            attacker_y: 5.0,
            attacker_z: 6.0,
        }
    }

    fn test_match() -> Match {
        let ticks = TickBuffer {
            frame_count: 6,
            player_count: 1,
            ticks: vec![50, 100, 200, 300, 400, 500],
            x: vec![1.0, 2.0, 3.0, 4.0, 5.0, 6.0],
            y: vec![0.0; 6],
            z: vec![0.0; 6],
            yaw: vec![0.0; 6],
            health: vec![100; 6],
            armor: vec![0; 6],
            flags: vec![3; 6],
            money: vec![800; 6],
            equip: vec![0; 6],
            gear: vec![0; 6],
            primary: vec![0; 6],
            secondary: vec![0; 6],
            active: vec![0; 6],
            clip: vec![0; 6],
            reserve: vec![0; 6],
        };
        Match {
            header: empty_header(),
            players: vec![player(0, "A", Side::Ct), player(1, "B", Side::T)],
            rounds: vec![
                knife_round(10, 90),
                live_round(1, 100, 164, 250),
                live_round(2, 250, 314, 400),
                live_round(3, 400, 464, 550),
            ],
            ticks,
            grenades: vec![GrenadeThrow {
                thrower: 0,
                kind: GrenadeKind::Smoke,
                start_tick: 180,
                detonate_tick: 200,
                end_tick: 220,
                points: vec![GrenadePoint {
                    tick: 190,
                    x: 10.0,
                    y: 20.0,
                    z: 0.0,
                }],
                fires: vec![FireCell {
                    x: 10.0,
                    y: 20.0,
                    start_tick: 200,
                    end_tick: 210,
                }],
            }],
            shots: vec![
                Shot {
                    tick: 80,
                    player: 0,
                    x: 0.0,
                    y: 0.0,
                    yaw: 0.0,
                },
                Shot {
                    tick: 210,
                    player: 0,
                    x: 1.0,
                    y: 1.0,
                    yaw: 90.0,
                },
            ],
            kills: vec![kill(80), kill(210), kill(480)],
            hurts: vec![],
            blinds: vec![],
            bomb_events: vec![],
            buy_events: vec![],
            stats: vec![],
            controller_dump: vec![],
        }
    }

    #[test]
    fn tutorial_stride_is_about_ten_hz() {
        assert_eq!(TUTORIAL_TICK_STRIDE, 6);
        assert_eq!(TUTORIAL_LIVE_ROUNDS, 2);
    }

    #[test]
    fn skips_knife_and_later_rounds_and_remaps_ticks() {
        let slice = slice_tutorial_match(&test_match(), 2).unwrap();
        assert_eq!(slice.origin_tick, 100);
        assert_eq!(slice.sliced.rounds.len(), 2);
        assert_eq!(slice.sliced.rounds[0].number, 1);
        assert_eq!(slice.sliced.rounds[0].start_tick, 0);
        assert_eq!(slice.sliced.rounds[0].freeze_end_tick, 64);
        assert_eq!(slice.sliced.rounds[1].start_tick, 150);
        assert_eq!(slice.sliced.rounds[1].end_tick, 300);
        assert_eq!(slice.sliced.header.playback_ticks, 316);
        assert_eq!(slice.sliced.header.score_ct, 1);
        assert_eq!(slice.sliced.header.score_t, 1);
        assert_eq!(slice.sliced.header.map_name, "de_mirage");
        assert_eq!(slice.sliced.ticks.ticks, vec![0, 100, 200, 300]);
        assert_eq!(slice.sliced.ticks.x, vec![2.0, 3.0, 4.0, 5.0]);
        assert_eq!(slice.sliced.ticks.frame_count, 4);
        assert_eq!(slice.sliced.kills.len(), 1);
        assert_eq!(slice.sliced.kills[0].tick, 110);
        assert_eq!(slice.sliced.shots.len(), 1);
        assert_eq!(slice.sliced.shots[0].tick, 110);
        assert_eq!(slice.sliced.grenades.len(), 1);
        assert_eq!(slice.sliced.grenades[0].start_tick, 80);
        assert_eq!(slice.sliced.grenades[0].points[0].tick, 90);
        assert_eq!(slice.sliced.grenades[0].fires[0].start_tick, 100);
    }

    #[test]
    fn errors_when_there_are_not_enough_live_rounds() {
        let mut m = test_match();
        m.rounds.retain(|r| r.is_knife || r.number == 1);
        let err = slice_tutorial_match(&m, 2).unwrap_err();
        assert!(err.contains("need 2"), "{err}");
    }

    #[test]
    fn emit_writes_exports_and_shards_long_soa_arrays() {
        let slice = slice_tutorial_match(&test_match(), 2).unwrap();
        let files = emit_tutorial_files(&slice.sliced, 10_000).unwrap();
        let names: Vec<&str> = files.iter().map(|f| f.name.as_str()).collect();
        assert!(names.contains(&"header.ts"));
        assert!(names.contains(&"players.ts"));
        assert!(names.contains(&"rounds.ts"));
        assert!(names.contains(&"events.ts"));
        assert!(names.contains(&"ticks.ts"));
        assert!(names.contains(&"constants.ts"));
        assert!(!names.contains(&"ticks_a.ts"));
        let header = files.iter().find(|f| f.name == "header.ts").unwrap();
        assert!(header.contents.contains("export const header"));
        assert!(header.contents.contains("de_mirage"));
        let constants = files.iter().find(|f| f.name == "constants.ts").unwrap();
        assert!(constants.contents.contains("tutorial|${TUTORIAL_MAP}"));
        assert!(constants.contents.contains("tutorial.dem"));

        let sharded = emit_tutorial_files(&slice.sliced, 3).unwrap();
        let shard_names: Vec<&str> = sharded.iter().map(|f| f.name.as_str()).collect();
        assert!(shard_names.contains(&"ticks_a.ts"));
        assert!(shard_names.contains(&"ticks_b.ts"));
        let ticks = sharded.iter().find(|f| f.name == "ticks.ts").unwrap();
        assert!(ticks.contents.contains("ticksA.concat(ticksB)"));
        assert!(ticks.contents.contains("from \"./ticks_a\""));
    }

    #[test]
    fn write_and_discover_use_repo_layout_paths() {
        let root =
            std::env::temp_dir().join(format!("cs2a-fix-{}-{}", std::process::id(), "discover"));
        let lib = root.join("apps/web/src/lib");
        std::fs::create_dir_all(&lib).unwrap();
        let nested = root.join("crates/demo");
        std::fs::create_dir_all(&nested).unwrap();
        let found = discover_tutorial_dir(&nested).unwrap();
        assert_eq!(found, lib.join("tutorial"));

        let slice = slice_tutorial_match(&test_match(), 2).unwrap();
        let summary = write_tutorial_fixture(
            &found,
            &slice,
            10_000,
            Some("export function hydrate() {}\n"),
        )
        .unwrap();
        assert!(found.join("header.ts").is_file());
        assert!(found.join("hydrate.ts").is_file());
        assert_eq!(summary.round_count, 2);
        assert_eq!(summary.map_name, "de_mirage");
        assert_eq!(summary.origin_tick, 100);
        std::fs::write(found.join("ticks_a.ts"), "stale\n").unwrap();
        write_tutorial_fixture(&found, &slice, 10_000, None).unwrap();
        assert!(!found.join("ticks_a.ts").exists());
        std::fs::remove_dir_all(&root).ok();
    }
}
