/** Generated by `cs2analyzer` tutorial export. Do not edit. */

export const header = {
  "map_name": "de_dust2",
  "tick_rate": 64.0,
  "tick_stride": 6,
  "duration_s": 3035.9688,
  "playback_ticks": 194302,
  "team_ct": "BIG",
  "team_t": "Team Spirit",
  "score_ct": 15,
  "score_t": 8
};
