/** Generated by `cs2analyzer` tutorial export. Do not edit. */

export const header = {
  map_name: "de_mirage",
  tick_rate: 64,
  tick_stride: 6,
  duration_s: 0,
  playback_ticks: 0,
  team_ct: "",
  team_t: "",
  score_ct: 0,
  score_t: 0,
};
